CREATE TABLE IF NOT EXISTS users (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(60) NOT NULL,
  birthdate VARCHAR(10) NOT NULL,
  UNIQUE(email)
);

CREATE TABLE IF NOT EXISTS reports (
  id INTEGER NOT NULL PRIMARY KEY,
  content TEXT NOT NULL
);
